server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库命名包含多个单词官方建议使用下划线连接
    url: jdbc:mysql://localhost:3306/auth_security?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    druid:
      # 初始化连接数
      initial-size: 5
      # 连接池中最小的空闲连接数
      min-idle: 5
      # 连接吃中最大的活跃连接数
      max-active: 20
      # 连接等待最大时间
      max-wait: 60000
      # 检测连接池中空闲连接的时间间隔
      time-between-eviction-runs-millis: 60000
      # 连接在池中保持空闲的最长时间
      min-evictable-idle-time-millis: 300000
      # 用于检测连接是否有效的SQL语句
      validation-query: SELECT 1 FROM DUAL
      # 当连接处于空闲状态时，是否执行验证查询
      test-while-idle: true
      # 当从连接池中借用连接时，是否执行验证查询
      test-on-borrow: false
      # 当归还连接给连接池时，是否执行验证查询
      test-on-return: false
      # 是否使用预处理语句来提高性能
      pool-prepared-statements: true
      # 每个连接允许的最大预处理语句数量
      max-pool-prepared-statement-per-connection-size: 20
      # 连接池中连接的过滤器列表
      # filters: stat,wall,log4j
      filters: stat,wall
      # 连接属性设置：是否合并SQL语句，设置慢查询阈值
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000

auth:
  captcha:
    enable: false
  info:
    base-package: top.kwseeker.authentication.biz

mybatis-plus:
  configuration:
    # 默认为 true
    map-underscore-to-camel-case: true
    # 打印sql语句到标准输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    db-config:
      # 重要说明：如果将配置放到 Nacos 时，请注意将 id-type 设置为对应 DB 的类型，否则会报错；详细见 https://gitee.com/zhijiantianya/yudao-cloud/issues/I5W2N0 讨论
      id-type: NONE # “智能”模式，基于 IdTypeEnvironmentPostProcessor + 数据源的类型，自动适配成 AUTO、INPUT 模式。
      # id-type: AUTO # 自增 ID，适合 MySQL 等直接自增的数据库
      # id-type: INPUT # 用户输入 ID，适合 Oracle、PostgreSQL、Kingbase、DB2、H2 数据库
      # id-type: ASSIGN_ID # 分配 ID，默认使用雪花算法。注意，Oracle、PostgreSQL、Kingbase、DB2、H2 数据库时，需要去除实体类上的 @KeySequence 注解
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-aliases-package: ${auth.info.base-package}.infrastructure.dal.po
  # type-handlers-package: ${auth.info.base-package}.infrastructure.dal.mybatis.type  # 发现会作用到Serialize参数上，TODO
