server:
  port: 8081

spring:
  profiles:
    active: dev

mybatis-plus:
  configuration:
    # 默认为 true
    map-underscore-to-camel-case: true
    # 打印sql语句到标准输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    db-config:
      # 重要说明：如果将配置放到 Nacos 时，请注意将 id-type 设置为对应 DB 的类型，否则会报错；详细见 https://gitee.com/zhijiantianya/yudao-cloud/issues/I5W2N0 讨论
      id-type: NONE # “智能”模式，基于 IdTypeEnvironmentPostProcessor + 数据源的类型，自动适配成 AUTO、INPUT 模式。
      # id-type: AUTO # 自增 ID，适合 MySQL 等直接自增的数据库
      # id-type: INPUT # 用户输入 ID，适合 Oracle、PostgreSQL、Kingbase、DB2、H2 数据库
      # id-type: ASSIGN_ID # 分配 ID，默认使用雪花算法。注意，Oracle、PostgreSQL、Kingbase、DB2、H2 数据库时，需要去除实体类上的 @KeySequence 注解
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-aliases-package: ${auth.info.base-package}.infrastructure.dal.po
  # type-handlers-package: ${auth.info.base-package}.infrastructure.dal.mybatis.type  # 发现会作用到Serialize参数上，TODO

auth:
  info:
    base-package: top.kwseeker.authentication.biz
